resources:
  - url: /hacsfiles/lovelace-xiaomi-vacuum-card/xiaomi-vacuum-card.js
    type: module

  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module

  - url: /hacsfiles/lovelace-xiaomi-vacuum-map-card/xiaomi-vacuum-map-card.js
    type: module

  - url: /hacsfiles/vertical-stack-in-card/vertical-stack-in-card.js
    type: module

  - url: /hacsfiles/lovelace-layout-card/layout-card.js
    type: module

title: Home
views:
  - title: Room
    icon: mdi:home
    panel: true
    cards:
      - type: custom:layout-card
        cards:
          - type: custom:vertical-stack-in-card
            cards:
              - type: picture-glance
                title: Alarm Clock
                entities:
                  - input_datetime.alarm_clock
                  - input_boolean.alarm_clock_status
                image: /local/alarm_clock.jpg
              - type: entities
                show_header_toggle: false
                entities:
                  - input_datetime.alarm_clock
                  - input_boolean.alarm_clock_status

          - type: custom:vertical-stack-in-card
            cards:
              - type: picture
                image: /local/ac-on.png
              - type: custom:simple-thermostat
                entity: climate.mitsubishi_ac
                name: false
                control:
                  hvac:
                    heat: false

          - type: custom:vertical-stack-in-card
            cards:
              - type: picture-entity
                entity: switch.bw_humidifier
                tap_action:
                  action: toggle
                state_image:
                  "on": /local/humidifier-on.jpg
                  "off": /local/humidifier-off.jpg
              - type: entities
                entities:
                  - entity: automation.humidifier_auto_on
                    name: Auto mode
                  - entity: sensor.room_humidity
                  - entity: sensor.bw_humidifier_wattage
                    name: Wattage

          - type: entities
            title: Sensors
            show_header_toggle: false
            entities:
              - entity: binary_sensor.motion_sensor_room
                secondary_info: last-changed
              - entity: sensor.illumination_34ce008bf588
                secondary_info: last-changed
              - entity: sensor.room_humidity
#            footer:
#              type: graph
#              entity: sensor.room_humidity
#              hours_to_show: 24
#              detail: 1

          - type: vertical-stack
            cards:
              - type: entities
                title: Lights
                show_header_toggle: true
                entities:
                  - light.room
                  - light.uta_table_lamp
                  - light.uta_room_lamp
                  - light.gateway_light_34ce008bf588

              - type: entities
                title: Garlands
                show_header_toggle: true
                entities:
                  - light.room_garland
#                  - light.window_garland
                  - light.uta_room_garland

  - title: Kitchen
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Sensors
            show_header_toggle: false
            entities:
              - entity: binary_sensor.motion_sensor_kitchen
                secondary_info: last-changed
              - entity: sensor.motion_sensor_kitchen
                secondary_info: last-changed
#            footer:
#              type: graph
#              entity: sensor.motion_sensor_kitchen
#              hours_to_show: 24
#              detail: 1

          - type: conditional
            conditions:
              - entity: media_player.googlehome2365
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.googlehome2365
          - type: conditional
            conditions:
              - entity: media_player.kitchen_tv
                state_not: "unavailable"
            card:
              type: media-control
              entity: media_player.kitchen_tv
          - type: picture-entity
            entity: media_player.samsung_tv
            tap_action:
              action: call-service
              service: media_player.toggle
              service_data:
                entity_id: media_player.samsung_tv
            state_image:
              "on": /local/tv-on.jpg
              "off": /local/tv-off.jpg

      - type: vertical-stack
        cards:
          - type: entities
            title: Kitchen Lights
            show_header_toggle: true
            entities:
              - light.kitchen_zone
              - light.kitchen_garland
              - light.yeelight_plus_strip
              - light.kitchen_candles
              - light.balcony
            footer:
              type: buttons
              entities:
                - entity: script.kitchen_romantic
                  icon: mdi:heart-multiple

          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: light.kitchen_candles
                tap_action:
                  action: toggle
                state_image:
                  "on": /local/candles-on.jpg
                  "off": /local/candles-off.jpg

  - title: Hall
    cards:
      - type: entities
        title: Sensors
        show_header_toggle: false
        entities:
          - entity: binary_sensor.motion_sensor_158d000155b56e
            secondary_info: last-changed
          - entity: binary_sensor.motion_sensor_wardrobe
            secondary_info: last-changed
          - entity: sensor.hall_light_level
            secondary_info: last-changed
      - type: entities
        title: Lights
        show_header_toggle: true
        entities:
          - light.hall
          - light.hall_night
          - light.wc_night
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:xiaomi-vacuum-card
            entity: vacuum.xiaomi_mi_robot
            name: false
            labels: false
          - type: picture-entity
            entity: vacuum.xiaomi_mi_robot
            tap_action:
              action: more-info
            hold_action:
              action: call-service
              service: vacuum.locate
              service_data:
                entity_id: vacuum.xiaomi_vacuum_cleaner
            image: /local/xiaomi-vacuum.jpg
          - type: entities
            entities:
              - entity: automation.weekdays_cleaning
                name: Scheduled cleaning

#  - title: Xmas lights
#    icon: mdi:christmas-lights
#    cards:
#      - type: entities
#        title: Kitchen Garlands
#        show_header_toggle: true
#        entities:
#          - light.kitchen_garland
#          - light.kitchen_window_garland
#          - light.cotton_garland
#          - light.christmas_table_tree
#      - type: entities
#        title: Room Garlands
#        show_header_toggle: true
#        entities:
#          - light.room_garland
#          - light.bed_garland
#          - light.window_garland
#          - light.uta_room_garland
#          - light.christmas_tree

  - title: Climate
    icon: mdi:weather-sunny
    panel: true
    cards:
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.broadlink_sensor_humidity
                hours_to_show: 24
                graph: line
              - type: sensor
                entity: sensor.room_temperature
                hours_to_show: 24
                graph: line
                name: Temperature

  - title: Devices
    icon: mdi:tablet
    cards:
      - type: entity-filter
        show_empty: false
        title: Alerts
        entities:
          - alert.humidifier_no_water
          - alert.lena_laptop_on_when_lena_not_home
          - alert.main_door
          - alert.humidifier_manual_switch_off
        state_filter:
          - "on"
      - type: entities
        entities:
          - entity: sensor.next_8
            format: relative
          - entity: sensor.next_42
            format: relative
          - entity: sensor.next_to_metro
            format: relative
      - type: entities
        entities:
          - person.mike
          - person.lena
          - person.utah
      - type: entities
        title: Group Motion Sensors
        show_header_toggle: false
        entities:
          - binary_sensor.no_motion
          - binary_sensor.no_motion_for_30_minutes
          - binary_sensor.no_motion_for_an_hour
      - type: entities
        title: Persistence
        show_header_toggle: false
        entities:
          - binary_sensor.someone_is_home
          - binary_sensor.nobody_is_home
          - binary_sensor.everyone_is_home
      - type: entity-filter
        title: Home
        entities:
          - device_tracker.nmap_lena_laptop
          - device_tracker.nmap_mike_laptop
          - device_tracker.nmap_xiaomi_redmi
          - device_tracker.nmap_galaxy_tab_a_2016
          - device_tracker.life360_lena
        state_filter:
          - "home"
      - type: entity-filter
        title: Away
        entities:
          - device_tracker.nmap_lena_laptop
          - device_tracker.nmap_mike_laptop
          - device_tracker.nmap_xiaomi_redmi
          - device_tracker.nmap_galaxy_tab_a_2016
          - device_tracker.life360_lena
        state_filter:
          - "not_home"
      - type: history-graph
        title: Laptops
        entities:
          - entity: device_tracker.nmap_lena_laptop
            name: Lena
          - entity: device_tracker.nmap_mike_laptop
            name: Mike
      - type: history-graph
        title: Mobiles
        entities:
          - entity: device_tracker.nmap_xiaomi_redmi
            name: Uta
          - entity: device_tracker.nmap_galaxy_tab_a_2016
            name: Mike
      - type: history-graph
        title: Proximity
        entities:
          - proximity.home_lena
          - sensor.dir_of_travel_lena
          - proximity.home_mike
          - sensor.dir_of_travel_mike

  - title: System
    icon: mdi:gauge
    cards:
      - type: vertical-stack
        cards:
          - type: gauge
            entity: sensor.cpu_temp
            name: CPU temp
          - type: gauge
            entity: sensor.processor_use
            name: Processor use
          - type: gauge
            entity: sensor.memory_use_percent
            name: Memory use
      - type: vertical-stack
        cards:
          - type: entity
            entity: sensor.time_online
          - type: entities
            entities:
              - entity: sensor.sunrise_time
                icon: mdi:weather-sunset-up
              - entity: sensor.sunset_time
                icon: mdi:weather-sunset-down
          - type: entities
            entities:
            - sensor.switch_battery_level
            - sensor.button_uta_battery_level
            - sensor.door_sensor_battery_level
            - sensor.motion_sensor_battery_level
            - sensor.button_hall_battery_level
            - sensor.button_kitchen_battery_level
#            - sensor.ac_battery_level
#            - sensor.motion_sensor_room_battery_level
#            - sensor.motion_sensor_kitchen_battery_level
#            - sensor.motion_sensor_wardrobe_battery_level

  - title: Settings
    icon: mdi:cogs
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            title: Kitchen button
            icon: mdi:radiobox-blank
            entities:
              - automation.button_kitchen_single
              - automation.button_kitchen_double
              - automation.button_kitchen_hold
          - type: entities
            title: Bed button
            icon: mdi:radiobox-blank
            entities:
              - automation.button_bed_single
              - automation.button_bed_double
              - automation.button_bed_hold
          - type: entities
            title: Uta button
            icon: mdi:radiobox-blank
            entities:
              - automation.button_uta_single
              - automation.button_uta_double
              - automation.button_uta_hold
          - type: entities
            title: Hall button
            icon: mdi:radiobox-blank
            entities:
              - automation.button_hall_single
              - automation.button_hall_hold

      - type: vertical-stack
        cards:
          - type: entities
            title: Motion [Room]
            icon: mdi:motion-sensor
            entities:
              - automation.room_motion_night
              - automation.room_no_motion_night

          - type: entities
            title: Motion [Kitchen]
            icon: mdi:motion-sensor
            show_header_toggle: false
            entities:
              - automation.kitchen_no_motion_30_min

          - type: entities
            title: Motion [Hall]
            icon: mdi:motion-sensor
            show_header_toggle: false
            entities:
              - automation.hall_motion_night
              - automation.hall_no_motion
              - automation.hall_no_motion_night

      - type: entities
        title: Door Sensor
        icon: mdi:door
        show_header_toggle: false
        entities:
          - automation.door_open_lights
          - automation.door_opened_evening_lights
          - automation.door_opened_notification
          - automation.door_closed_notification

      - type: entities
        title: Humidifier
        icon: mdi:water-percent
        show_header_toggle: false
        entities:
          - automation.humidifier_auto_on
          - automation.humidifier_auto_off
          - automation.humidifier_auto_off_in_the_morning
          - automation.humidifier_auto_on_after_lunch