- platform: template
  sensors:
    mike_is_moving_home_after_work:
      value_template: >-
        {{ is_state("sensor.dir_of_travel_mike", "towards")
           and is_state("binary_sensor.workday_sensor", "on") }}
      delay_on:
        minutes: 5

    mike_is_moving_home_after_work_within_5_km:
      value_template: >-
        {{ states('proximity.home_mike')|float < 5000
           and is_state("sensor.dir_of_travel_mike", "towards")
           and is_state("binary_sensor.workday_sensor", "on") }}
      delay_on:
        minutes: 2

    humidifier_water_tank_empty:
      value_template: >-
        {% set wattage = states('sensor.bw_humidifier_wattage')|float %}
        {{ wattage > 0.5 and wattage < 3 }}
      delay_on:
        minutes: 5
      delay_off:
        minutes: 5

    humidifier_manual_switch_off:
      value_template: >-
        {{ states('sensor.bw_humidifier_wattage')|float < 0.1
           and is_state("switch.bw_humidifier", "on") }}
      delay_on:
        minutes: 1
      delay_off:
        minutes: 1

    door_is_open_more_than_2_minutes:
      value_template: >-
        {{ is_state('binary_sensor.door_window_sensor_158d0001700885', 'on') }}
      delay_on:
        minutes: 2

    lena_laptop_on_while_lena_away:
      value_template: >-
        {{ is_state('device_tracker.nmap_lena_laptop', 'home')
           and not is_state('person.lena', 'home') }}
      delay_off:
        minutes: 5

    tv_is_on:
      value_template: >-
        {{ not is_state('media_player.kitchen_tv', 'unavailable')
           and not is_state('media_player.kitchen_tv', 'unknown') }}