- platform: workday
  country: BY
  add_holidays:
    - '2020-01-06'
    - '2020-04-27'

- platform: tod
  name: dark time
  after: sunset
  before: sunrise

- platform: tod
  name: time to sleep
  after: '22:00'
  before: '06:00'

- platform: tod
  name: dnd
  after: '23:00'
  before: '7:00'