  - platform: broadlink
    friendly_name: "Broadlink Mini"
    host: 192.168.0.47
    mac: 'b4:43:0d:f9:32:b1'

  - platform: broadlink
    friendly_name: "Broadlink RM Pro"
    host: 192.168.0.96
    mac: 'b4:43:0d:fb:d2:31'
    timeout: 15
    switches:
      candles:
        friendly_name: "Candles"
        command_on: 'JgCIAAABJJQRFBETEhMRFBETEhQQFBETEjgROBE4EjcSOBE4EjcSOBETEhMSExETExISExETEhMSNxM3ETgSNxM3ETgSNxM3EQAFFgABJkkTAAw9AAElSRIADD8AASRKEwAMPgABJEoSAAw+AAEkShIADD8AASRKEgAMPwABJEoSAAw+AAElShEADQU='
        command_off: "JgCYAAABJ5EUEBURExETERQSExISERQSEjYUNhM2EzYUNhM2FDUUNhM2ExITERQRExITERQRExITERQ2EzYTNhQ1FDYSNxQ1FAAFFAABJkgUAAw9AAElSRQADDwAASRLEQAMPwABJEoSAAw/AAElSRMADD4AASVJEwAMPQABJUoRAAw/AAElSRMADD4AASVJEwAMPgABJkgTAA0F"
      garland:
        friendly_name: "Garland"
        command_on: 'sgCaABEQEQ8REBEQERARDxIPERAREBEQERAQEBEQERAREBEPEg8REBEQEUIiIBEPEhAhICIgIg8SHyIQERARICIPESASDyIgIg8SDxIPERAREBEQERARDxIgIh8SDyIQESARQiIgERARECIgISAiDxIgIg8SDxIfIhARIBEQIiAhEBEQERAREBEPEg8REBIPESAiIBEQIg8RIBEABdwAAAAAAAAAAAAAAAAAAA=='
        command_off: 'sgCgABEQEBAREBEQERARDxEQERAREBEQEQ8SDxEQERAREBEPERAREBEQERARQhEQERARDxIPIiARECIPEg8SHyIQERARICEQESERDyIgIg8SDxIPERAREBEQERARIBEQERAhISIgIVMREBEQEQ8RECIgERAiDxEQESAiEBEPEiAhEBIgEQ8iICEQEg8REBEQERAREBEPEiAREBEQISAiICIABdwAAAAAAAAAAA=='
      balcony:
        friendly_name: "Balcony"
        command_on: 'sgDGABEQEBAREBEQEBAREBEQEQ8REBEQERAQERAQEBEQEBEQERARDxEQERAREBAQERAREBAREBAREBEPERAREBEQEBEQEBEQEBAREBEQEEMREBAREBEhEBEPESEhICERECEhEBEPERARIRAQIiARECEQERARDxEQERAREBEQESAhEBEQERARICEQEVMQEBEQERAhEBEQESAiICEQESAiDxEQERARIBEQISEQESEQEBAREBEQERARDxEQESEhEBAREBARISEQEQAF3AAA'
        command_off: 'sgCwAA8REBEPERAREBEPEg8SDxEQEQ8REBEQEQ8SDxEQERARDxEQERARDxEQERAREBEPEg8REBEPERARD0QQERARIBEQERARDyIgISEQECIgERAREBEPIg8SICEQESAREBEQEQ8REBEQERARECEgERARECIfIiBUDxIPEiAREBAQERAiICEgERAiIBEPERARECIPESAiEBAhEQ8REBEQERAREBEPEg8iIBEQEBAiICIgAAXcAAAAAAAAAAA='
      hall_night:
        friendly_name: "Hall Night"
        command_on: 'sgC+ABEQERAREBEPERAREBEQEQ8REBEQERARDxEQERAREBEPERAREBEQEQ8REBEQERAQEBEQERAREBEPERAREBEQEQ8REBEQERARDxEQEUIiEBEgIRARICIQERARIBEQIRARICIPEiAREBEPIiAiDxEQERAREBEQERARDxIgISAiIBEQIiAQQyIPESAiDxIgIRAREBEgERAiDxEhIRARIBEQERAhISEQERARDxIPERAREBEQESAiICEhEBAiIBEABdwAAAAAAAAAAAAA'
        command_off: 'sgCSABARDxIPERAREBEQEQ8SDxEQEQ9EEBEQERAREBEgERAREBEQERAhEBEgERAiIBEQIRAREBEgIiAREBEQEQ8SDxEQERAREBEQISEhEBEgIg8SD0QQEQ8SDxIPESERDxIPERARECIPESERECEhEQ8iDxIPESEhIBIQEBAREBEQERAREBEQEBAiICIPEiAiDxEQAAXcAAAAAAAA'
      hall:
        friendly_name: "Hall"
        command_on: '6QkyABDJESIRIxEjESMhEhEjESMRIyISESMhExEiESIRIxAjECMhEhEjESMRIhEiESMRIiEWAAAAAAAA'
        command_off: '6QkyABDJECMRIxEjESMgExAjESMRIyETECMRIyETIBMRIyETIBQQIxAkECQQIxAjESMQIyEWAAAAAAAA'
      room_light:
        friendly_name: "Room Light"
        command_on: '6QkyABHIEiIRIxAkECMhEhEjESMRIyETECMQIyETIBMhExAjESQhEhEjESMQIxAjESMhExEmAAAAAAAA'
        command_off: '6Q8yABHIEiIRIxIhEiMhEhEjESIRIyISESIRIyESIhIhExEiIhIRIxAjECMRIxEjECMhEhEmAAAAAAAA'
      rf_socket_01:
        command_on: 'sgg0AAoAATwLHh8KHwoLHh8KCx4fCwseCx4LHh8KCx4LHgseCx4LHh8KCx4LHgseHwseCwseHwwAAAAA'
        command_off: 'si40AAoAATwLHh8KHwoLHh8KCx4fCgseCx4LHh8KCx4LHgseCx4LHh8KCx4LHgseCx4fCgseHwsAAAAA'
      rf_socket_02:
        command_on: 'si80AAkAAT0KHx4LHgsKHx8LCx8fCwsfCx8LHx8KCx8KHwofCh8KHx4LCh8LHgseHwsfCh8LCyAAAAAA'
        command_off: 'sik0AAoAAT0LHh8KHwsLHh8KCx4fCgseCx4LHh8LCx4LHgsfCx4LHh8LCh8LHgseCx4fCh8LCx8AAAAA'
