- alias: Room - Motion [night]
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_room
    to: 'on' 
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_time
        state: 'on'
      - condition: state
        entity_id: binary_sensor.time_to_sleep
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.room_light
        below: 300
  action:
    - service: light.turn_on
      entity_id: light.hall_night
    - service: script.gateway_night_light

- alias: Room - No motion [night]
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_room
    to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_34ce008bf588