# HALL: No motion
- alias: No motion
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
    for:
      minutes: 4
  action:
    - service: light.turn_off
      entity_id: light.hall

# HALL: Motion [night mode]
- alias: Motion [night mode]
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'on' 
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_time
        state: 'on'
      - condition: state
        entity_id: binary_sensor.time_to_sleep
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.room_light
        below: 300
  action:
    - service: light.turn_on
      entity_id: light.kitchen_garland
    - service: script.gateway_night_light

# HALL: No motion at night [1 minute]
- alias: No motion at night [1 minute]
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
  condition:
    - condition: state
      entity_id: binary_sensor.dark_time
      state: 'on'
    - condition: time
      before: '06:10:00'
  action:
    - service: homeassistant.turn_off
      data:
        entity_id: light.gateway_light_34ce008bf588

# HALL: No motion at night [2 minutes]
- alias: No motion at night [2 minutes]
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
    for:
      minutes: 1
  condition:
    - condition: state
      entity_id: binary_sensor.dark_time
      state: 'on'
    - condition: time
      before: '06:10:00'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_garland

# HALL: No motion at night [5 minutes]
- alias: No motion at night [5 minutes]
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
    for:
      minutes: 4
  condition:
    - condition: state
      entity_id: binary_sensor.dark_time
      state: 'on'
    - condition: time
      before: '06:10:00'
  action:
    - service: light.turn_off
      entity_id: light.hall_night