- alias: Hall - No motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
    for:
      minutes: 4
  action:
    - service: light.turn_off
      entity_id: light.hall

- alias: Hall - Motion [night]
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'on' 
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_time
        state: 'on'
      - condition: state
        entity_id: binary_sensor.time_to_sleep
        state: 'on'
      - condition: numeric_state
        entity_id: sensor.room_light
        below: 300
  action:
    - service: light.turn_on
      entity_id: light.kitchen_garland
    - service: light.turn_on
      entity_id: light.hall_night

- alias: Hall - No motion [night]
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000155b56e
    to: 'off'
    for:
      minutes: 4
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_time
        state: 'on'
      - condition: state
        entity_id: binary_sensor.time_to_sleep
        state: 'on'
  action:
    - service: light.turn_off
      entity_id: light.kitchen_garland
    - service: light.turn_off
      entity_id: light.hall_night