# Telegram notifications
- alias: Door opened notify
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  action:
    - service: notify.telegram_bot
      data:
        title: '*Door sensor*'
        message: "Door opened!"

- alias: Door closed notify
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'off'
  action:
    - service: notify.telegram_bot
      data:
        title: '*Door sensor*'
        message: "Door closed!"

# Turn ON hall light on open (only if coming in)
- alias: Door opened
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  condition:
    condition: and
    conditions:
      # TODO: use light sensor when I have it
      - condition: time
        after: '13:00:00'
        before: '03:00:00'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000155b56e
        state: 'off'
  action:
    - service: light.turn_on
      entity_id: light.hall

# Turn ON kitchen warm led in the evening on door open
- alias: Door opened in the evening
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.dark_time
        state: 'on'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000155b56e
        state: 'off'
  action:
    - delay:
        seconds: 1
    - service: light.turn_on
      entity_id: light.yeelight_plus_strip
