# Turn ON christmas lights on open
- alias: Door opened xmas 16 till 18
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.season
        state: 'winter'
      - condition: time
        after: '16:00:00'
        before: '18:00:00'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000155b56e
        state: 'off'
  action:
    - delay:
        seconds: 1
    - service: light.turn_on
      entity_id: light.room_christmas_garlands

# Turn ON christmas lights on open
- alias: Door opened xmas 18 till 21
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.season
        state: 'winter'
      - condition: time
        after: '18:00:00'
        before: '21:00:00'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000155b56e
        state: 'off'
  action:
    - delay:
        seconds: 1
    - service: light.turn_on
      entity_id: light.all_christmas_garlands

# Turn ON christmas lights on open
- alias: Door opened xmas 21 till midnight
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.door_window_sensor_158d0001700885
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.season
        state: 'winter'
      - condition: time
        after: '21:00:00'
        before: '23:59:59'
      - condition: state
        entity_id: binary_sensor.motion_sensor_158d000155b56e
        state: 'off'
  action:
    - delay:
        seconds: 1
    - service: light.turn_on
      entity_id: light.kitchen_garlands