- alias: 'Telegram help'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/help'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: '*Help*'
        target: '{{ trigger.event.data.user_id }}'
        disable_notification: true
        message: >
          Available commands:

          /ping

          /temp

          /eva

          /ac

- alias: 'Telegram keyboard'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/keyboard'
  action:
    - service: telegram_bot.send_message
      data_template:
        keyboard: ["/ping, /eva, /ac, /temp"]

- alias: 'Telegram remove message'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/remove_message'
  action:
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'