- alias: 'Telegram eva'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_command
    event_data:
      command: '/eva'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: '*Xiaomi Mi Robot*'
        target: '{{ trigger.event.data.user_id }}'
        message: 'Yes, master?'
        disable_notification: true
        inline_keyboard:
          - "Start cleaning:/eva_run, Stop:/eva_dock"
          - "Cancel:/remove_message"

- alias: 'Telegram eva start cleanup'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/eva_run'
  action:
    - service: telegram_bot.delete_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
    - service: notify.telegram_bot
      data:
        message: 'Starting the cleanup!'
    - service: vacuum.start
      entity_id: vacuum.xiaomi_mi_robot

- alias: 'Telegram eva go back to dock'
  initial_state: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/eva_dock'
  action:
    - service: notify.telegram_bot
      data:
        message: 'Stopped'
    - service: vacuum.stop
      entity_id: vacuum.xiaomi_mi_robot