- name: Mike
  id: mike
  device_trackers:
    - device_tracker.life360_mike
    - device_tracker.bt_galaxy_tab_a_2016
    - device_tracker.nmap_galaxy_tab_a_2016

- name: Lena
  id: lena
  device_trackers:
    - device_tracker.life360_lena
    - device_tracker.nmap_lena_mobile

- name: Utah
  id: utah
  device_trackers:
    - device_tracker.nmap_xiaomi_redmi
    - device_tracker.bt_xiaomi_redmi