# Hall button
- alias: Button hall [single]
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d6aa5d
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.all_garlands

- alias: Button hall [hold]
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d6aa5d
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.all_lights_but_hall