# Kitchen button
- alias: Button kitchen [single]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d6209b
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.kitchen_garlands

- alias: Button kitchen [double]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d6209b
      click_type: double
  action:
    - service: script.turn_on
      entity_id: script.kitchen_romantic

- alias: Button kitchen [hold]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d6209b
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.kitchen
    - service: light.turn_off
      entity_id: light.kitchen_garlands
