# Uta room button
- alias: Uta Button [single]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.room_uta

- alias: Uta Button [double]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: double
  action:
    - service: light.toggle
      entity_id: light.uta_room_garland

- alias: Uta Button [hold]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.room_uta
    - service: light.turn_off
      entity_id: light.uta_room_garland
