# Room button
- alias: Switch [double click]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001837b93
      click_type: double
  action:
    - service: light.toggle
      entity_id: light.room_garland

- alias: Switch [single click]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001837b93
      click_type: single
  action:
    - service: light.toggle
      entity_id: light.room_garlands

- alias: Switch [hold]
  initial_state: true
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001837b93
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.all_lights