- alias: Button Uta [single]
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: single
  action:
    - service: light.toggle
      data:
        entity_id: light.room_uta

- alias: Button Uta [double]
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: double
  action:
    - service: light.toggle
      entity_id: light.uta_room_garland

- alias: Button Uta [hold]
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001d8e1fe
      click_type: hold
  action:
    - service: light.turn_off
      entity_id: light.room_uta
    - service: light.turn_off
      entity_id: light.uta_room_garland
