moonlight_turn_on:
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        command:
          - turn on

moonlight_turn_off:
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        command:
          - turn off

moonlight_turn_on_night_mode:
  sequence:
    - service: remote.send_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        command:
          - turn on
    - service: remote.send_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        num_repeats: 5
        command:
          - dim down
    - service: remote.send_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        command:
          - orange