learn_moonlight:
  sequence:
    - service: remote.learn_command
      data:
        entity_id: remote.rm_mini
        device: moonlight
        command:
          - turn on
          - turn off
          - dim up
          - dim down
          - red
          - green
          - blue
          - white
          - orange
          - yellow
          - turquoise
          - aqua
          - purple
          - pink