esphome:
  name: tv_garland
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "100-27"
  password: "147896321"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.0.57
    gateway: 192.168.0.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "hass-kg100"

ota:
  password: "hass-kg100"

# Enable Web server
web_server:
  port: 80

status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - light.toggle: sonoff_light

output:
  - platform: gpio
    id: relay
    pin: GPIO12

light:
  - platform: binary
    id: sonoff_light
    name: sonoff_tv_garland
    output: relay