esphome:
  name: uta_room_lamp
  platform: ESP8266
  board: esp01_1m
  #esp8266_restore_from_flash: yes

wifi:
  ssid: "100-27"
  password: "147896321"
  fast_connect: true
  manual_ip:
    static_ip: 192.168.0.90
    gateway: 192.168.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sonoff Room Table Lamp"
    password: "7MwSu4TDjP87"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "hass-kg100"

ota:
  password: "hass-kg100"

# Enable Web server
web_server:
  port: 80

status_led:
  pin:
    number: GPIO13
    inverted: True

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    on_press:
      - switch.toggle: sonoff_switch

switch:
  - platform: template
    optimistic: true
    id: sonoff_switch
    name: uta_room_lamp
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on:
          id: led
          brightness: 75%
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: led

  - platform: gpio
    id: relay
    pin: GPIO12

output:
  - platform: esp8266_pwm
    id: basic_green_led
    pin:
      number: GPIO13
      inverted: True

light:
  - platform: monochromatic
    output: basic_green_led
    id: led