  - platform: template
    sensors:
      motion_sensor_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (motion sensor)
        value_template: '{{ states.binary_sensor.motion_sensor_158d000155b56e.attributes.battery_level | int }}'
      door_sensor_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (door)
        value_template: '{{ states.binary_sensor.door_window_sensor_158d0001700885.attributes.battery_level | int }}'
      switch_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (switch)
        value_template: "{{ state_attr('binary_sensor.switch_158d0001837b93', 'battery_level') | int }}"
      button_kitchen_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (button kitchen)
        value_template: '{{ states.binary_sensor.switch_158d0001d6209b.attributes.battery_level | int }}'
      button_hall_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (button hall)
        value_template: '{{ states.binary_sensor.switch_158d0001d6aa5d.attributes.battery_level | int }}'
      button_uta_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (button uta)
        value_template: '{{ states.binary_sensor.switch_158d0001d8e1fe.attributes.battery_level | int }}'
      button_05_battery_level:
        unit_of_measurement: "%"
        friendly_name: Battery (button temp)
        value_template: '{{ states.binary_sensor.switch_158d0001d6a946.attributes.battery_level | int }}'
